export const FunctionComponent = 0;
export const ClassComponent = 1;
export const IndeterminateComponent = 2; // 在还未能识别是函数组件还是类组件时, 会将 fiber 的 tag 设置为这个值
export const HostRoot = 3; // 根 fiber
export const HostPortal = 4; // Portal 的 tag
export const HostComponent = 5; // 原生 DOM 节点的 tag
export const HostText = 6; // 文本
export const Fragment = 7;
export const Mode = 8;
export const ContextConsumer = 9;
export const ContextProvider = 10;
export const ForwardRef = 11;
export const Profiler = 12;
export const SuspenseComponent = 13;
export const MemoComponent = 14;
export const SimpleMemoComponent = 15;
export const LazyComponent = 16;
export const IncompleteClassComponent = 17;
export const DehydratedFragment = 18;
export const SuspenseListComponent = 19;
export const ScopeComponent = 21;
export const OffscreenComponent = 22;
export const LegacyHiddenComponent = 23;
export const CacheComponent = 24;
export const TracingMarkerComponent = 25;
